accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UserCreateView #UserRedirectView,
from .forms import CustomAuthenticationForm
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
	# path('', UserRedirectView.as_view(), name='redirect'),
	path('signup/', UserCreateView.as_view(), name='signup'),
	path('login/', auth_views.LoginView.as_view(
			template_name='accounts/login.html',
			redirect_authenticated_user=True,
			authentication_form=CustomAuthenticationForm), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
	path('password-reset/', auth_views.PasswordResetView.as_view(
			template_name='accounts/password_reset.html',
			email_template_name='accounts/password_reset_email.html',
			subject_template_name='accounts/password_reset_subject.txt',
			success_url=reverse_lazy('accounts:password_reset_done')
			), name='password_reset'),
	path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
			template_name='accounts/password_reset_done.html'    
			), name='password_reset_done'),
	path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
			template_name='accounts/password_reset_confirm.html',
			success_url=reverse_lazy('accounts:password_reset_complete')
			), name='password_reset_confirm'),
	path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='accounts/password_reset_complete.html'    
			), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	path('', views.PostListView.as_view(), name='post_list'),
	path('create/', views.PostCreateView.as_view(), name='post_create'),
	path('<str:slug>-<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
	path('<str:slug>-<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
	path('<str:slug>-<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
	path('<str:slug>-<int:pk>/like-toggle/', views.PostLikeToggleView.as_view(), name='post_like_toggle'),
	path('<str:slug>-<int:pk>/dislike-toggle/', views.PostDislikeToggleView.as_view(), name='post_dislike_toggle'),
	path('<str:slug>-<int:pk>/comments/<int:comment_pk>/like-toggle/', views.CommentLikeToggleView.as_view(), 
		name='comment_like_toggle'),
	path('<str:slug>-<int:pk>/comments/<int:comment_pk>/dislike-toggle/', views.CommentDislikeToggleView.as_view(), 
		name='comment_dislike_toggle'),
	path('<str:category>/', views.CategoryPostListView.as_view(), name='category_posts')
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from .managers import UserManager
from django.utils.translation import gettext_lazy as _

# Create your models here.

class User(PermissionsMixin, AbstractBaseUser):
	first_name = models.CharField(_('first name'), max_length=30)
	last_name = models.CharField(_('last name'), max_length=30)
	email = models.EmailField(
		_('email address'), 
		unique=True, 
		error_messages={
			'unique': _('A user with that email already exists.')
		})
	username = models.CharField(_('username'), max_length=25, blank=True)
	date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
	is_active = models.BooleanField(
		_('active'), 
		default=True,
		help_text=_(
			'Designates whether this user should be treated as active. '
			'Unselect this instead of deleting accounts.'
		)
	)
	is_staff = models.BooleanField(
		_('staff status'), 
		default=False, 
		help_text=_('Designates whether the user can log into the admin site.')
	)

	objects = UserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['first_name', 'last_name']

	class Meta:
		verbose_name = 'user'
		verbose_name_plural = 'users'

	def __str__(self):
		return self.full_name

	def save(self, *args, **kwargs):
		if not self.username:
			# check this and fix the possibility of an integrity error
			self.username = f'{self.first_name}{self.pk}'
			
		return super(User, self).save(*args, **kwargs)

	@property
	def full_name(self):
		return f'{self.first_name} {self.last_name}'

	def email_user(self, subject, message, from_email=None, **kwargs):
		send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from userprofiles.models import Profile
from django.utils.translation import gettext_lazy as _
from django.db import transaction
from PIL import Image


class UserSignUpForm(UserCreationForm):

	password1 = forms.CharField(
        label=_("Password"),
        strip=False,
		widget=forms.PasswordInput(
			attrs={
				'auto-complete': 'new-password',
				'class': 'text-input-acc password-input'
			}
		)
	)

	password2 = forms.CharField(
	    label=_('Confirm Password'),
	    strip=False,
		widget=forms.PasswordInput(
			attrs={
				'auto-complete': 'new-password',
				'class': 'text-input-acc password-input'
			}
		)
	)

	class Meta:
		model = get_user_model()
		fields = ('email', 'first_name', 'last_name')
		widgets = {
			'email': forms.EmailInput(
				attrs={'class': 'text-input-acc standard-input'}
			),
			'first_name': forms.TextInput(
				attrs={'class': 'text-input-acc standard-input'}
			),
			'last_name': forms.TextInput(
				attrs={'class': 'text-input-acc standard-input'}
			)
		}

	def __init__(self, *args, **kwargs):
		kwargs.setdefault('label_suffix', '')
		return super(UserSignUpForm, self).__init__(*args, **kwargs)

	@transaction.atomic
	def save(self, commit=True):
		user = super().save(commit=False)

		if commit:
			user.save()
			profile = Profile.objects.create(user=user)

		return user


class CustomAuthenticationForm(AuthenticationForm):
	username = UsernameField(
		widget=forms.EmailInput(
			attrs={'class': 'text-input-acc standard-input'}
		)
	)

	password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
        	attrs={
        		'autocomplete': 'new-password',
        		'class': 'text-input-acc password-input'
        	}
        ),
	)

	def __init__(self, request=None, *args, **kwargs):
		kwargs.setdefault('label_suffix', '')
		super(CustomAuthenticationForm, self).__init__(request, *args, **kwargs)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserSignUpForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.views.generic import View, CreateView
from django.conf import settings

# Create your views here.

# class UserRedirectView(View):

# 	def get(self, request, *args, **kwargs):
# 		if request.user.is_authenticated:
# 			return redirect('userprofiles:profile', user=request.user.profile.display_name)
# 		else:
# 			return redirect('accounts:login')


class UserCreateView(SuccessMessageMixin, CreateView):
	model = get_user_model()
	form_class = UserSignUpForm
	template_name = 'accounts/signup.html'
	success_message = 'Your Account has been succesfully Created, Login to Continue!'

	def get_success_url(self):
		return reverse(settings.LOGIN_URL)

accounts/templates/accounts/login.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %} Login Page {% endblock title %}

{% block content %}
	{% if messages %}
		{% for message in messages %}
			<div class="message message-{{ message.tags}}">
				{{ message }}
			</div>
			<div class="dummy-space"></div>
		{% endfor %}
	{% endif %}
	<div class="container-acc">
		<div class="fm-col">
			<div class="fm-col__header">
				<h2>Login</h2>
			</div>
			{% if form.errors %}
			<div class="login-error">
				<p>Invalid Username or Password.</p>
			</div>
			{% endif %}
			<div class="fm-col__form-container">
				<form method="POST">
					{% csrf_token %}
					<div class="form-row">
						{{ form.username.label_tag }}
						<div class="input-container">
							<i class="far fa-envelope"></i>
							{{ form.username }}
						</div>
					</div>
					<div class="form-row">
						{{ form.password.label_tag }}
						<div class="input-container">
							<i class="fas fa-lock"></i>
							{{ form.password }}
							<a class="password-toggler">
								<i class="far fa-eye-slash"></i>
								<i class="far fa-eye"></i>
							</a>
						</div>
						<p>
							<a href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
						</p>
					</div>
					<div class="form-row">
						<button type="submit" class="submit-button ">LOGIN</button>
					</div>
				</form>
			</div>
		</div>
		<div class="img-col">			
			<div class="img-col__svg-container">
				<img src="{% static 'accounts/img/login.svg' %}" alt="login svg" class="img-col__svg">
			</div>
			<div class="img-col__message">
				<p>
					Don't Have an Account? <a href="{% url 'accounts:signup' %}">Signup here</a>
				</p>
			</div>
		</div>
	</div>
{% endblock content %}

{% block script %}
	<script src="{% static 'accounts/js/main.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/logout.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %}Logout Page{% endblock title %}

{% block content %}
	<h2>You have been logged out!</h2>
	<a href="{% url 'accounts:login' %}">Click here to Login Again</a>
{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends "blog/base.html" %}

{% block title %} Password Reset {% endblock title %}

{% block content %}
<div class="container-acc">
  <div class="fm-col">
    <div class="fm-col__header">
      <h2>Forgot Password</h2>
    </div>
    <div class="fm-col__form-container">
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <label for="{{ form.email.id_for_label}}">Email Address</label>
          <div class="input-container">
            <i class="far fa-envelope"></i>
            <input type="email" name="{{ form.email.name }}" autocomplete="email" class="text-input-acc standard-input" 
              max_length="{{ form.email.field.max_length }}" id="{{ form.email.id_for_label}}" required />
          </div>
        </div>
        <div class="form-row">
          <button type="submit" class="submit-button">Request Password Reset</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends "blog/base.html" %}

{% block title %} Password Reset Done {% endblock title %}

{% block content %}
<div class="message message-success">
  Your Password has been successfully reset!
</div>
<div class="dummy-space"></div>
<p>
  <a href="{% url 'accounts:login' %}">Login here</a>
</p>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %} Password Reset Confirm {% endblock title %}

{% block content %}
  {% if validlink %}
  <div class="container-acc">
    <div class="fm-col">
      <div class="fm-col__header">
        <h2>Reset Your Password</h2>
      </div>
      <div class="fm-col_form-container">
        <form method="POST">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-row">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="input-container">
              <i class="fas fa-lock"></i>
              <input type="password" name="{{ field.name }}" autocomplete="new-password" class="text-input-acc password-input"
                id="{{ field.id_for_label }}" required />
              <a class="password-toggler">
                <i class="far fa-eye-slash"></i>
                <i class="far fa-eye"></i>
              </a>
            </div>
            {{ field.errors }}
          </div>
          {% endfor %}
          <div class="form-row">
            <button type="submit" class="submit-button">Reset Password</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% else %}
  <div class="message message-info">
    The password reset link is invalid, possibly because it has already been used. Please request a new password reset
  </div>
  {% endif %}
{% endblock content %}

{% block script %}
<script src="{% static 'accounts/js/main.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/password_reset_done.html
{% extends "blog/base.html" %}

{% block title %} Password Reset Done {% endblock title %}

{% block content %}
<div class="message message-info">
  We've emailed you instructions for resetting your password.<br />
  If an account exists with the email you entered, you should receive them shortly.
</div>
<div class="dummy-space"></div>
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
{{ user.get_username }}, You are receiving this email because you requested a password reset for your Xoszlog account.
Click on the link below to reset your password:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the above link does not work, please copy and paste the URL in a new browser window instead.


Xoszlog Team
{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %} SignUp Page {% endblock title %}

{% block content %}
	<div class="container-acc">
		<div class="img-col">			
			<div class="img-col__svg-container">
				<img src="{% static 'accounts/img/signup.svg' %}" alt="signup svg" class="img-col__svg">
			</div>
			<div class="img-col__message">
				<p>
          Already Have An Account? <a href="{% url 'accounts:login' %}">Login here</a>
				</p>
			</div>
		</div>
		<div class="fm-col">
			<div class="fm-col__header">
				<h2>Sign Up</h2>
			</div>
			<div class="fm-col__form-container">
				<form method="POST">
					{% csrf_token %}
          <div class="form-row">
            {{ form.email.label_tag }}
            <div class="input-container">
              <i class="far fa-envelope"></i>
              {{ form.email }}
            </div>
            {{ form.email.errors }}
          </div>
          <div class="form-row">
            {{ form.first_name.label_tag }}
            <div class="input-container">
              <i class="far fa-user"></i>
              {{ form.first_name }}
            </div>
            {{ form.first_name.errors }}
          </div>
          <div class="form-row">
            {{ form.last_name.label_tag }}
            <div class="input-container">
              <i class="far fa-user"></i>
              {{ form.last_name }}
            </div>
            {{ form.last_name.errors }}
          </div>
          <div class="form-row">
            {{ form.password1.label_tag }}
            <div class="input-container">
              <i class="fas fa-lock"></i>
              {{ form.password1 }}
              <a class="password-toggler">
                <i class="far fa-eye-slash"></i>
                <i class="far fa-eye"></i>
              </a>
            </div>
            {{ form.password1.errors }}
          </div>
          <div class="form-row">
            {{ form.password2.label_tag }}
            <div class="input-container">
              <i class="fas fa-lock"></i>
              {{ form.password2 }}
              <a class="password-toggler">
                <i class="far fa-eye-slash"></i>
                <i class="far fa-eye"></i>
              </a>
            </div>
            {{ form.password2.errors }}
          </div>
					<div class="form-row">
						<button type="submit" class="submit-button">SIGN UP</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

{% block script %}
	<script src="{% static 'accounts/js/main.js' %}"></script>
{% endblock script %}