accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import UserCreateView #UserRedirectView,
from .forms import CustomAuthenticationForm
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
	# path('', UserRedirectView.as_view(), name='redirect'),
	path('signup/', UserCreateView.as_view(), name='signup'),
	path('login/', auth_views.LoginView.as_view(
			template_name='accounts/login.html',
			redirect_authenticated_user=True,
			authentication_form=CustomAuthenticationForm), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
	path('password-reset/', auth_views.PasswordResetView.as_view(
			template_name='accounts/password_reset.html',
			email_template_name='accounts/password_reset_email.html',
			subject_template_name='accounts/password_reset_subject.txt',
			success_url=reverse_lazy('accounts:password_reset_done')
			), name='password_reset'),
	path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
			template_name='accounts/password_reset_done.html'    
			), name='password_reset_done'),
	path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
			template_name='accounts/password_reset_confirm.html',
			success_url=reverse_lazy('accounts:password_reset_complete')
			), name='password_reset_confirm'),
	path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='accounts/password_reset_complete.html'    
			), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	path('', views.PostListView.as_view(), name='post_list'),
	path('create/', views.PostCreateView.as_view(), name='post_create'),
	path('<str:slug>-<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
	path('<str:slug>-<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
	path('<str:slug>-<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
	path('<str:slug>-<int:pk>/like-toggle/', views.PostLikeToggleView.as_view(), name='post_like_toggle'),
	path('<str:slug>-<int:pk>/dislike-toggle/', views.PostDislikeToggleView.as_view(), name='post_dislike_toggle'),
	path('<str:slug>-<int:pk>/comments/<int:comment_pk>/like-toggle/', views.CommentLikeToggleView.as_view(), 
		name='comment_like_toggle'),
	path('<str:slug>-<int:pk>/comments/<int:comment_pk>/dislike-toggle/', views.CommentDislikeToggleView.as_view(), 
		name='comment_dislike_toggle'),
	path('<str:category>/', views.CategoryPostListView.as_view(), name='category_posts')
]

userprofiles/urls.py
from django.urls import path
from . import views


app_name = 'userprofiles'

urlpatterns = [
	path('', views.UserProfileView.as_view(), name='profile'),
	path('edit-profile/', views.UserProfileEditView.as_view(), name='profile_edit'),
	path('liked/posts/', views.UserLikedPostsView.as_view(), name='user_liked_posts'),
	path('disliked/posts/', views.UserDislikedPostsView.as_view(), name='user_disliked_posts'),
	path('drafts/', views.UserDraftedPostsView.as_view(), name='user_drafted_posts'),
	path('drafts/<str:slug>-<int:pk>/', views.UserDraftPreviewView.as_view(), name='user_draft_preview'),
	path('drafts/<str:slug>-<int:pk>/publish/', views.UserDraftPublishView.as_view(), name='user_draft_publish'),
	path('drafts/<str:slug>-<int:pk>/update/', views.UserDraftUpdateView.as_view(), name='user_draft_update'),
	path('drafts/<str:slug>-<int:pk>/delete/', views.UserDraftDeleteView.as_view(), name='user_draft_delete'),
	path('drafts/<str:category>/', views.CategoryUserDraftedPosts.as_view(), name='category_user_drafts'),
	path('<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
	path('<str:username>/posts/', views.UserPublishedPostsView.as_view(), name='user_published_posts'),
	path('<str:username>/comments/', views.UserCommentListView.as_view(), name='user_comments'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from PIL import Image
from django.utils.text import slugify
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import readtime

# Create your models here.

class Category(models.Model):
	name = models.CharField(max_length=25)
	date_added = models.DateField(auto_now_add=True)
	date_updated = models.DateField(auto_now=True)

	class Meta:
		verbose_name_plural = 'Categories'

	def __str__(self):
		return self.name


class PostQuerySet(models.QuerySet):

	def published(self):
		return self.filter(status='pd').order_by('-date_published')

	def drafted(self):
		return self.filter(status='dt').order_by('-date_updated')


class Post(models.Model):
	DRAFT = 'dt'
	PUBLISHED = 'pd'

	STATUS_CHOICES = (
		(DRAFT, 'Draft'),
		(PUBLISHED, 'Published')
	)

	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, 
								related_name='posts', related_query_name='post')
	title = models.CharField(max_length=120)
	content = models.TextField(blank=True, null=True) # because of tinymce validation errors, maybe try only blank
	slug = models.SlugField(max_length=120, default='', editable=False)
	read_time = models.CharField(max_length=25, default='', editable=False)
	status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=DRAFT)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts', 
								related_query_name='post', default=1)
	thumbnail = models.ImageField(default="default_tb.png", upload_to='post_thumbnails')
	likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_likes', blank=True)
	dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='post_dislikes', blank=True)
	objects = PostQuerySet.as_manager()
	date_published = models.DateTimeField(null=True, editable=False)
	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title, allow_unicode=True)
		self.read_time = readtime.of_text(self.content)
		super().save(*args, **kwargs)

		img = Image.open(self.thumbnail.path)
		if img.width > 640 or img.height > 640:
			output_size = (640, 640)
			img.thumbnail(output_size, Image.ANTIALIAS)
			img.save(self.thumbnail.path, optimize=True)

	def get_absolute_url(self):
		return reverse('blog:post_detail', kwargs={'pk': self.pk, 'slug': self.slug})

	def publish(self):
		self.status = self.PUBLISHED
		self.date_published = timezone.now()
		self.save()

	def get_num_comments(self):
		return self.comments.count()

	def get_num_likes(self):
		return self.likes.count()

	def get_num_dislikes(self):
		return self.dislikes.count()


class Comment(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
							   related_name='comments', related_query_name='comment')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', 
							 related_query_name='comment')
	content = models.TextField(_('Leave a Comment'))
	likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_likes', blank=True)
	dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_dislikes', blank=True)
	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['-date_created']

	def get_num_likes(self):
		return self.likes.count()

	def get_num_dislikes(self):
		return self.dislikes.count()

blog/forms.py
from django import forms
from .models import Post, Comment


class BaseModelForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		kwargs.setdefault('label_suffix', '')
		return super(BaseModelForm, self).__init__(*args, **kwargs)


class PostForm(BaseModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'thumbnail')
        widgets = {
            'content': forms.Textarea(
                attrs={'class': 'form-content'}
            )
        }


class CommentForm(BaseModelForm):

    class Meta:
        model = Comment
        fields = ('content', )

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.conf import settings
from django.views.generic.detail import SingleObjectMixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import JsonResponse
from django.db import transaction
from django.urls import reverse
from django.db.models import Prefetch
from urllib import parse
from django.views.generic import (
	View,
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView,
)

# Create your views here.


class CustomListView(ListView):
	paginate_by = 4


class PostListView(CustomListView):

	def get_queryset(self):
		return Post.objects.select_related('author__profile', 'category').published()


class PostDetailView(SingleObjectMixin, View):
	query_pk_and_slug = True

	def get_queryset(self):
		comments = Prefetch(
			'comments', 
			queryset=Comment.objects.select_related('author').prefetch_related('likes', 'dislikes')
		)
		return Post.objects.select_related('author__profile', 'category').prefetch_related(
			comments, 'likes', 'dislikes'
		).published()

	def get(self, request, *args, **kwargs):
		obj = self.get_object()
		form = CommentForm()
		context = {
			'object': obj,
			'comment_form': form
		}
		return render(request, 'blog/post_detail.html', context)

	def post(self, request, *args, **kwargs):
		form = CommentForm(data=request.POST)
		if form.is_valid():
			with transaction.atomic():
				obj = self.get_object()
				instance = form.save(commit=False)
				instance.post = obj
				instance.author = request.user
				instance.save()

		return redirect(obj.get_absolute_url())


class PostCreateView(CreateView):
	model = Post
	form_class = PostForm

	def get_context_data(self, **kwargs):
		kwargs['action'] = 'create'
		return super(PostCreateView, self).get_context_data(**kwargs)

	def get_success_url(self):
		return reverse('userprofiles:user_draft_preview', kwargs={'slug': self.object.slug, 'pk': self.object.pk})

	def form_valid(self, form):
		form.instance.author = self.request.user
		messages.info(self.request, 'Draft has been Created!')
		return super().form_valid(form)


class PostUpdateView(UpdateView):
	query_pk_and_slug = True
	form_class = PostForm

	def get_queryset(self):
		return self.request.user.posts.published()

	def get_context_data(self, **kwargs):
		kwargs['action'] = 'update'
		return super(PostUpdateView, self).get_context_data(**kwargs)

	def form_valid(self, form):
		# form.instance.author = self.request.user
		messages.success(self.request, 'Your Post has been Successfully Updated!')
		return super().form_valid(form)


class PostDeleteView(DeleteView):
	query_pk_and_slug = True

	def get_queryset(self):
		return self.request.user.posts.published()

	def get_success_url(self):
		return reverse('blog:post_list')


class ActionManagerMixin(SingleObjectMixin):

	def get_object_action_managers(self):
		obj = self.get_object()
		return [obj.likes, obj.dislikes] if self.action == 'like_toggle' else [obj.dislikes, obj.likes]


class ObjectActionToggleView(ActionManagerMixin, View):

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			# the reason we're using request.Meta... and not request.path or request.get_full_path() to get the
			# next url (the url the user should be redirected to after logging in i.e the page they were on before 
			# they were asked to login) is because it returns the url for like/dislike toggle and GET requests 
			# are not allowed on that url (only ajax POST is allowed), thereby resulting in a 405 error.
			# so yeah, we'll like to avoid that 
			redirect_to = parse.urlparse(request.META['HTTP_REFERER']).path
			response = {'redirect_url': f"{reverse(settings.LOGIN_URL)}?next={redirect_to}"}
			return JsonResponse(response, status=401)

		if request.is_ajax():
			main_obj_manager, opp_obj_manager = self.get_object_action_managers()

			if request.user in main_obj_manager.all():
				main_obj_manager.remove(request.user)

			elif request.user in opp_obj_manager.all():
				opp_obj_manager.remove(request.user)
				main_obj_manager.add(request.user)

			else:
				main_obj_manager.add(request.user)

			response = {
				'main_elem_count': main_obj_manager.count(),
				'opp_elem_count': opp_obj_manager.count()
			}

			return JsonResponse(response, status=200)


class PostLikeToggleView(ObjectActionToggleView):
	# model = Post
	query_pk_and_slug = True
	action = 'like_toggle'

	def get_queryset(self):
		return Post.objects.published()


class PostDislikeToggleView(ObjectActionToggleView):
	# model = Post
	query_pk_and_slug = True
	action = 'dislike_toggle'

	def get_queryset(self):
		return Post.objects.published()


class CommentLikeToggleView(ObjectActionToggleView):
	model = Comment
	pk_url_kwarg = 'comment_pk'
	action = 'like_toggle'


class CommentDislikeToggleView(ObjectActionToggleView):
	model = Comment
	pk_url_kwarg = 'comment_pk'
	action = 'dislike_toggle'


class CategoryPostListView(PostListView):

	def get_queryset(self):
		category = get_object_or_404(Category, name=self.kwargs['category'])
		return super(CategoryPostListView, self).get_queryset().filter(category=category)

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<title>{% block title %}{% endblock title %}</title>
		<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap" 
					rel="stylesheet" />
		<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
	</head>
	<body>
		<div class="page-wrapper">
			<header class="page-header">
				<h1><a href="{% url 'blog:post_list' %}">Blog App</a></h1>
				<nav class="nav-bar">
					<ul class="nav-bar__items">
						{% if user.is_authenticated %}
							<li>
								<a href="{% url 'blog:post_list' %}">Blog</a>
							</li>
							<li>
								<a href="{% url 'userprofiles:profile' %}">Profile</a>
							</li>
							<li>
								<a href="{% url 'accounts:logout' %}">Logout</a>
							</li>
						{% else %}
							<li>
								<a href="{% url 'accounts:login' %}">Login</a>
							</li>
							<li>
								<a href="{% url 'accounts:signup' %}">SignUp</a>
							</li>
						{% endif %}
					</ul>
					<div class="nav-bar__hamburger">
						<div class="block-1"></div>
						<div class="block-2"></div>
						<div class="block-3"></div>
					</div>
				</nav>
			</header>
			<main role="main" class="main-content">
				{% block messages %}
				{% endblock messages %}
				{% if messages %}
					<div class="message-container">
						{% for message in messages %}
							<div class="message message-{{ message.tags }}">
								<p>{{ message }}</p>
								<span class="close">&times;</span>
							</div>
						{% endfor %}
					</div>
				{% endif %}

				{% block content %}
				{% endblock content %}
			</main>
			<footer class="page-footer">
				<p>&copy; {% now "Y" %} Blog App</p>
			</footer>
		</div>
		
		<script src="{% static 'js/main.js' %}"></script>
		{% block script %}
		{% endblock script %}
	</body>
</html>

blog/templates/blog/draft_list.html
{% extends "blog/base.html" %}

{% block title %} Drafts {% endblock title %}

{% block content %}
<div class="container-blog">
	{% for instance in object_list %}
	<article class="post-item">
		<div class="post-item__thumbnail">
			<img src="{{ instance.thumbnail.url }}" alt="{{ instance.title }} image" />
		</div>
		<div class="post-item__title">
			<h2>
        <a href="{% url 'userprofiles:draft_preview' slug=instance.slug pk=instance.pk %}">
					{{ instance.title }}
				</a>
      </h2>
		</div>
		<div class="post-item__category">
			<p> 
				<a href="#">{{ instance.category }}</a>
			</p>
		</div>
		<div>
			<p>{{ instance.content | truncatewords:20 | safe }}</p>
		</div>
	</article>
	{% empty %}
	<div>NOTHING TO DISPLAY!</div>
	{% endfor %}
</div>

{% if is_paginated %}
	<div class = "pagination">
		{% if page_obj.has_previous %}
			<a class="pagination-action" href="?page=1" title="First Page">
				<i class="fas fa-angle-double-left fa-2x"></i>
			</a>
			<a class="pagination-action" href="?page={{ page_obj.previous_page_number }}" title="Previous Page">
				<i class="fas fa-angle-left fa-2x"></i>
			</a>
		{% endif %}

		{% for pg in page_obj.paginator.page_range %}
			{% if page_obj.number == pg %}
				<a class="pagination-number pagination-current">{{ pg }}</a>
			{% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
				<a class="pagination-number" href="?page={{ pg }}">{{ pg }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="pagination-action" href="?page={{ page_obj.next_page_number }}" title="Next Page">
				<i class="fas fa-angle-right fa-2x"></i>
			</a>
			<a class="pagination-action" href="?page={{ page_obj.paginator.num_pages }}" title="Last Page">
				<i class="fas fa-angle-double-right fa-2x"></i>
			</a>
		{% endif %}
	</div>

	<div class="logs-length">
		<p> {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }} posts. </p>
	</div>
{% endif %}
{% endblock content %}

blog/templates/blog/draft_preview.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %}{{ object.title }} &mdash; Preview{% endblock title %}

{% block content %}
<div class="post-detail">
  <div class="post-detail__title">
    <h1>{{ object.title }} (Draft Preview)</h1>
    <a href="#">{{ object.category }}</a> 
  </div>
  <div>
    <div>
      <form method="POST" action="{% url 'blog:draft_publish' slug=object.slug pk=object.pk %}">
        {% csrf_token %}
        <button type="submit">Publish Post</button>
      </form>
    </div>
    <div>
      <a href="{% url 'blog:draft_update' slug=object.slug pk=object.pk %}">
        Update Draft
      </a>
    </div>
    <div>
      <form method="POST" action="{% url 'blog:draft_delete' slug=object.slug pk=object.pk %}">
        {% csrf_token %}
        <button type="submit">Delete Draft</button>
      </form>
    </div>
  </div>
  <div class="post-detail__thumbnail">
    <img src="{{ object.thumbnail.url }}" alt="{{ instance.title }} image" />
  </div>
  <div class="post-detail__content">
    {{ object.content | safe }}
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
<div class="post-detail">
  <div class="post-detail__title">
    <h2>{{ object.title }}</h2>
    <a href="{% url 'blog:category_posts' category=object.category %}">{{ object.category }}</a> 
  </div>
  <div class="post-item__author">
    <div class="author-img-container">
      <img src="{{ object.author.profile.image.url }}" alt="{{ object.author }}" class="author-img" />
    </div>
    <div class="author-info">
      <h4>
        <a href="{% url 'userprofiles:user_profile' username=object.author.username %}">{{ object.author }}</a>
      </h4>
      <small>Published on {{ object.date_published.date }}</small>
      <small><i class="far fa-clock"></i> {{ object.read_time }}</small>
    </div>
  </div>
  {% if request.user == object.author %}
  <div>
    <div>
      <a href="{% url 'blog:post_update' slug=object.slug pk=object.pk %}">Update Post</a>
    </div>
    <div>
      <form method="POST" action="{% url 'blog:post_delete' slug=object.slug pk=object.pk %}">
        {% csrf_token %}
        <button type="submit">Delete Post</button>
      </form>
    </div>
  </div>
  {% endif %}
  <div class="post-detail__thumbnail">
    <img src="{{ object.thumbnail.url }}" alt="Image for {{ object.title }} Post" />
  </div>
  <div class="post-detail__content">
    {{ object.content | safe }}
  </div>
  <div>
    <p>
      <a href="{% url 'blog:post_like_toggle' slug=object.slug pk=object.pk %}" 
        class="like-toggler {% if request.user in object.likes.all %}selected{% endif %}">
        <i class="fas fa-thumbs-up"></i>
        <span>{{ object.get_num_likes }}</span>
      </a>
      <a href="{% url 'blog:post_dislike_toggle' slug=object.slug pk=object.pk %}" 
        class="dislike-toggler {% if request.user in object.dislikes.all %}selected{% endif %}">
        <i class="fas fa-thumbs-up"></i>
        <span>{{ object.get_num_dislikes }}</span>
      </a>
    </p>
  </div>

  <div>
    <form method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit">Save Comment</button>
    </form>
  </div>
  <div id="comments">
    {% for comment in object.comments.all %}
      <div>
        <h4>{{ comment.author }}</h4>
        <p>{{ comment.content }}</p>
        <p>      
          <a href="{% url 'blog:comment_like_toggle' slug=object.slug pk=object.pk comment_pk=comment.pk %}" 
            class="like-toggler {% if request.user in comment.likes.all %}selected{% endif %}">
            <i class="fas fa-thumbs-up"></i>
            <span>{{ comment.get_num_likes }}</span>
          </a>
          <a href="{% url 'blog:comment_dislike_toggle' slug=object.slug pk=object.pk comment_pk=comment.pk %}" 
            class="dislike-toggler {% if request.user in comment.dislikes.all %}selected{% endif %}">
            <i class="fas fa-thumbs-up"></i>
            <span>{{ comment.get_num_dislikes }}</span>
          </a>
        </p>
      </div>
    {% endfor %}
  </div>

</div>
{% endblock content %}

{% block script %}
  <script src="{% static 'blog/js/main.js' %}"></script>
{% endblock script %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %}Post {% if action == 'create' %} Create {% else %} Update {% endif %}{% endblock title %}

{% block content %}
  <div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">
        {% if action == 'create' %} Draft this Post {% else %} Update Your Post {% endif %}
      </button>
    </form>
  </div>
{% endblock content %}

{% block script %}
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="{% static 'blog/js/tinymceConfig.js' %}"></script>
{% endblock script %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %} Blog {% endblock title %}

{% block content %}
<div class="container-blog">
	<div class="add-post">
		<a href="{% url 'blog:post_create' %}" class="add-link">ADD POST+</a>
	</div>
	<section class="posts-container">
		{% for instance in object_list %}
			<article class="post-item">
				<div class="post-item__author">
					<div class="author-img-container">
						<img src="{{ instance.author.profile.image.url }}" alt="{{ instance.author }} image" class="author-img" />
					</div>
					<div class="author-info">
						<h4>
							<a href="{% url 'userprofiles:user_profile' username=instance.author.username %}">{{ instance.author }}</a>
						</h4>
						<small>{{ instance.date_published.date }}</small>
						<small><i class="far fa-clock"></i> {{ instance.read_time }}</small>
					</div>
				</div>
				<div class="post-item__thumbnail">
					<img src="{{ instance.thumbnail.url }}" alt="{{ instance.title }} image" />
				</div>
				<div class="post-item__title">
					<h2><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></h2>
				</div>
				<div class="post-item__category">
					<p> 
						<a href="{% url 'blog:category_posts' category=instance.category %}">{{ instance.category }}</a>
					</p>
				</div>
				<div class="post-item__content">
					<p>{{ instance.content | truncatewords:20 | safe }}</p>
				</div>
			</article>
		{% empty %}
			<div>
				<p>NOTHING TO DISPLAY!</p>
			</div>
		{% endfor %}
	</section>
</div>

{% if is_paginated %}
	<div class="pagination">
		{% if page_obj.has_previous %}
			<a class="pagination-action" href="?page=1" title="First Page">
				<i class="fas fa-angle-double-left fa-2x"></i>
			</a>
			<a class="pagination-action" href="?page={{ page_obj.previous_page_number }}" title="Previous Page">
				<i class="fas fa-angle-left fa-2x"></i>
			</a>
		{% endif %}

		{% for pg in page_obj.paginator.page_range %}
			{% if page_obj.number == pg %}
				<a class="pagination-number pagination-current">{{ pg }}</a>
			{% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
				<a class="pagination-number" href="?page={{ pg }}">{{ pg }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="pagination-action" href="?page={{ page_obj.next_page_number }}" title="Next Page">
				<i class="fas fa-angle-right fa-2x"></i>
			</a>
			<a class="pagination-action" href="?page={{ page_obj.paginator.num_pages }}" title="Last Page">
				<i class="fas fa-angle-double-right fa-2x"></i>
			</a>
		{% endif %}
	</div>

	<div class="logs-length">
		<p> {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }} posts. </p>
	</div>
{% endif %}

{% endblock content %}