blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
	path('', views.PostListView.as_view(), name='post_list'),
	path('create/', views.PostCreateView.as_view(), name='post_create'),
	path('<str:slug>-<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
	path('<str:slug>-<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
	path('<str:slug>-<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
	path('<str:slug>-<int:pk>/like-toggle/', views.PostLikeToggleView.as_view(), name='post_like_toggle'),
	path('<str:slug>-<int:pk>/dislike-toggle/', views.PostDislikeToggleView.as_view(), name='post_dislike_toggle'),
	path('<str:slug>-<int:pk>/comments/<int:comment_pk>/like-toggle/', views.CommentLikeToggleView.as_view(), 
		name='comment_like_toggle'),
	path('<str:slug>-<int:pk>/comments/<int:comment_pk>/dislike-toggle/', views.CommentDislikeToggleView.as_view(), 
		name='comment_dislike_toggle'),
	path('<str:category>/', views.CategoryPostListView.as_view(), name='category_posts')
]

userprofiles/urls.py
from django.urls import path
from . import views


app_name = 'userprofiles'

urlpatterns = [
	path('', views.UserProfileView.as_view(), name='profile'),
	path('edit-profile/', views.UserProfileEditView.as_view(), name='profile_edit'),
	path('liked/posts/', views.UserLikedPostsView.as_view(), name='user_liked_posts'),
	path('disliked/posts/', views.UserDislikedPostsView.as_view(), name='user_disliked_posts'),
	path('drafts/', views.UserDraftedPostsView.as_view(), name='user_drafted_posts'),
	path('drafts/<str:slug>-<int:pk>/', views.UserDraftPreviewView.as_view(), name='user_draft_preview'),
	path('drafts/<str:slug>-<int:pk>/publish/', views.UserDraftPublishView.as_view(), name='user_draft_publish'),
	path('drafts/<str:slug>-<int:pk>/update/', views.UserDraftUpdateView.as_view(), name='user_draft_update'),
	path('drafts/<str:slug>-<int:pk>/delete/', views.UserDraftDeleteView.as_view(), name='user_draft_delete'),
	path('drafts/<str:category>/', views.CategoryUserDraftedPosts.as_view(), name='category_user_drafts'),
	path('<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
	path('<str:username>/posts/', views.UserPublishedPostsView.as_view(), name='user_published_posts'),
	path('<str:username>/comments/', views.UserCommentListView.as_view(), name='user_comments'),
]

userprofiles/models.py
from django.db import models
from django.conf import settings
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    image = models.ImageField(default='default_pp.png', upload_to='profile_pictures')
    date_of_birth = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.user}'s Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 150 or img.width > 150:
            output_size = (150, 150)
            img = img.resize(output_size, Image.LANCZOS)
            img.save(self.image.path, optimize=True)

userprofiles/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from .models import Profile
from blog.forms import BaseModelForm


class UserUpdateForm(UserChangeForm):
	password = None
	readonly_fields = ('email', )
			
	class Meta:
		model = get_user_model()
		fields = ('email', 'first_name', 'last_name', 'username')
		widgets = {
			'email': forms.EmailInput(attrs={
				'class': 'read-only text-input-acc pfl-col__input-box'
			}),
			'first_name': forms.TextInput(attrs={
				'class': 'text-input-acc pfl-col__input-box'
			}),
			'last_name': forms.TextInput(attrs={
				'class': 'text-input-acc pfl-col__input-box'
			}),
			'username': forms.TextInput(attrs={
				'class': 'text-input-acc pfl-col__input-box'
			}),
			# 'date_joined': forms.DateInput(attrs={
			# 	'class': 'text-input-acc read-only pfl-col__input-box'
			# }),
		}

	def __init__(self, *args, **kwargs):
		kwargs.setdefault('label_suffix', '')
		super(UserUpdateForm, self).__init__(*args, **kwargs)
		for field in self.readonly_fields:
			self.fields[field].disabled = True

	def clean_username(self):
		cleaned_data = super(UserUpdateForm, self).clean()
		username = cleaned_data['username']
		if get_user_model().objects.filter(username__iexact=username).exists() and self.instance.username != username:
			self.add_error('username', 'This username has been already been taken')

		return username


class ProfileUpdateForm(BaseModelForm):

	class Meta:
		model = Profile
		fields = ('bio', 'date_of_birth', 'image')
		widgets = {
			'bio': forms.Textarea(attrs={
				'class': 'text-input-acc pfl-col__input-box'
			}),
			'date_of_birth': forms.DateInput(attrs={
				'type': 'date',
				'class': 'text-input-acc pfl-col__input-box'
			})
		}

userprofiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from blog.models import Comment, Category
from blog.views import PostListView, CustomListView
from blog.forms import PostForm
from django.urls import reverse
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import (
	View,
	ListView,
	DetailView,
	UpdateView, 
	DeleteView
)

# Create your views here.

class UserProfileView(View):

	def get(self, request, *args, **kwargs):
		try:
			username = self.kwargs['username']
			user = get_object_or_404(
				get_user_model(),
				username__iexact=username
			)
		except KeyError:
			if not request.user.is_authenticated:
				return redirect('blog:post_list')
			
			user = request.user

		context = {
			'user_obj': user,
			'num_drafted': user.posts.drafted().count(),
			'num_published': user.posts.published().count(),
			'num_liked': user.post_likes.count(),
			'num_disliked': user.post_dislikes.count(),
			'num_comments': user.comments.count()
		}
		return render(request, 'userprofiles/profile.html', context)


class UserProfileEditView(View):

	def get(self, request, *args, **kwargs):
		user_form = UserUpdateForm(instance=request.user)
		profile_form = ProfileUpdateForm(instance=request.user.profile)
		context = {
			'user_form': user_form,
			'profile_form': profile_form
		}
		return render(request, 'userprofiles/profile_edit.html', context)

	def post(self, request, *args, **kwargs):
		user_form = UserUpdateForm(data=request.POST, instance=request.user)
		profile_form = ProfileUpdateForm(data=request.POST, files=request.FILES, instance=request.user.profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Your Profile has been Updated Successfully!')
			return redirect('userprofiles:profile')

		return render(request, 'userprofiles/profile_edit.html', {'user_form': user_form, 'profile_form': profile_form})


class UserPublishedPostsView(PostListView):

	def get_queryset(self):
		user = get_object_or_404(get_user_model(), username__iexact=self.kwargs['username'])
		return super(UserPublishedPostsView, self).get_queryset().filter(author=user)


class UserDraftedPostsView(CustomListView):
	template_name = 'userprofiles/draft_list.html'

	def get_queryset(self):
		return self.request.user.posts.select_related('category').drafted()


class UserDraftPreviewView(DetailView):
	template_name = 'userprofiles/draft_preview.html'

	def get_queryset(self):
		return self.request.user.posts.select_related('category').drafted()


class UserDraftUpdateView(UpdateView):
	form_class = PostForm
	query_pk_and_slug = True

	def get_queryset(self):
		return self.request.user.posts.drafted()

	def get_success_url(self):
		messages.info(self.request, 'Draft has been Updated!')
		return reverse('userprofiles:user_draft_preview', kwargs={'slug': self.object.slug, 'pk': self.object.pk})


class UserDraftDeleteView(DeleteView):
	query_pk_and_slug = True

	def get_queryset(self):
		return self.request.user.posts.drafted()

	def get_success_url(self):
		messages.info(self.request, 'Draft has been Deleted!')
		return reverse('userprofiles:user_drafted_posts')


class UserDraftPublishView(SingleObjectMixin, View):
	query_pk_and_slug = True

	def get_queryset(self):
		return self.request.user.posts.drafted()

	def post(self, request, *args, **kwargs):
		obj = self.get_object()
		obj.publish()
		messages.success(request, 'Post has been Published Successfully!')
		return redirect(obj.get_absolute_url())


class CategoryUserDraftedPosts(CustomListView):
	template_name = 'userprofiles/draft_list.html'

	def get_queryset(self):
		category = get_object_or_404(Category, name__iexact=self.kwargs['category'])
		return self.request.user.posts.drafted().filter(category=category)


class UserLikedPostsView(CustomListView):

	def get_queryset(self):
		return self.request.user.post_likes.select_related('author__profile', 'category').all()


class UserDislikedPostsView(CustomListView):

	def get_queryset(self):
		return self.request.user.post_dislikes.select_related('author__profile', 'category').all()


class UserCommentListView(ListView):
	paginate_by = 6
	template_name = 'userprofiles/comment_list.html'

	def get_queryset(self):
		user = get_object_or_404(
			get_user_model().objects.select_related('profile'), 
			username__iexact=self.kwargs['username']
		)
		return user.comments.select_related('post').all()

	def get_context_data(self, **kwargs):
		kwargs['username'] = self.kwargs['username']
		return super(UserCommentListView, self).get_context_data(**kwargs)
		

userprofiles/templates/userprofiles/comment_list.html
{% extends "blog/base.html" %}

{% block title %} {{ username }}'s Comments {% endblock title %}

{% block content %}
<div class="container-blog">
	<div>
		<p> {{ username }}'s Comments </p>
	</div>
	<section class="posts-container">
		{% for instance in object_list %}
			<article class="post-item">
				<div class="post-item__author">
					<div class="author-img-container">
						<img src="{{ instance.author.profile.image.url }}" alt="{{ instance.author }} image" class="author-img" />
					</div>
					<div class="author-info">
						<h4>
							<a href="{% url 'userprofiles:user_profile' username=username %}">{{ instance.author }}</a>
						</h4>
					</div>
				</div>
				<div>
					<p>
						<a href="{{ instance.post.get_absolute_url }}#comments">
							{{ instance.content | truncatewords:20 }}
						</a>
					</p>
				</div>
			</article>
		{% empty %}
			<div>
				<p>NOTHING TO DISPLAY!</p>
			</div>
		{% endfor %}
	</section>
</div>
{% endblock content %}

userprofiles/templates/userprofiles/draft_list.html
{% extends "blog/base.html" %}

{% block title %} Drafts {% endblock title %}

{% block content %}
<div class="container-blog">
	<section class="posts-container">
		{% for instance in object_list %}
			<article class="post-item">
				<div class="post-item__thumbnail">
					<img src="{{ instance.thumbnail.url }}" alt="{{ instance.title }} image" />
				</div>
				<div class="post-item__title">
					<h2>
						<a href="{% url 'userprofiles:user_draft_preview' slug=instance.slug pk=instance.pk %}">
							{{ instance.title }}
						</a>
					</h2>
				</div>
				<div class="post-item__category">
					<p> 
						<a href="{% url 'userprofiles:category_user_drafts' category=instance.category %}">
							{{ instance.category }}
						</a>
					</p>
				</div>
				<div>
					<p>{{ instance.content | truncatewords:20 | safe }}</p>
				</div>
			</article>
		{% empty %}
			<div>
				<p>NOTHING TO DISPLAY!</p>
			</div>
		{% endfor %}
	</section>
</div>

{% if is_paginated %}
	<div class = "pagination">
		{% if page_obj.has_previous %}
			<a class="pagination-action" href="?page=1" title="First Page">
				<i class="fas fa-angle-double-left fa-2x"></i>
			</a>
			<a class="pagination-action" href="?page={{ page_obj.previous_page_number }}" title="Previous Page">
				<i class="fas fa-angle-left fa-2x"></i>
			</a>
		{% endif %}

		{% for pg in page_obj.paginator.page_range %}
			{% if page_obj.number == pg %}
				<a class="pagination-number pagination-current">{{ pg }}</a>
			{% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
				<a class="pagination-number" href="?page={{ pg }}">{{ pg }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="pagination-action" href="?page={{ page_obj.next_page_number }}" title="Next Page">
				<i class="fas fa-angle-right fa-2x"></i>
			</a>
			<a class="pagination-action" href="?page={{ page_obj.paginator.num_pages }}" title="Last Page">
				<i class="fas fa-angle-double-right fa-2x"></i>
			</a>
		{% endif %}
	</div>

	<div class="logs-length">
		<p> {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }} posts. </p>
	</div>
{% endif %}
{% endblock content %}

userprofiles/templates/userprofiles/draft_preview.html
{% extends "blog/base.html" %}

{% load static %}

{% block title %}{{ object.title }} &mdash; Preview{% endblock title %}

{% block content %}
<div class="post-detail">
  <div class="post-detail__title">
    <h1>{{ object.title }} (Draft Preview)</h1>
    <a href="{% url 'userprofiles:category_user_drafts' category=object.category %}">{{ object.category }}</a> 
  </div>
  <div>
    <div>
      <form method="POST" action="{% url 'userprofiles:user_draft_publish' slug=object.slug pk=object.pk %}">
        {% csrf_token %}
        <button type="submit">Publish Post</button>
      </form>
    </div>
    <div>
      <a href="{% url 'userprofiles:user_draft_update' slug=object.slug pk=object.pk %}">
        Update Draft
      </a>
    </div>
    <div>
      <form method="POST" action="{% url 'userprofiles:user_draft_delete' slug=object.slug pk=object.pk %}">
        {% csrf_token %}
        <button type="submit">Delete Draft</button>
      </form>
    </div>
  </div>
  <div class="post-detail__thumbnail">
    <img src="{{ object.thumbnail.url }}" alt="{{ instance.title }} image" />
  </div>
  <div class="post-detail__content">
    {{ object.content | safe }}
  </div>
</div>
{% endblock content %}

{% block script %}
  <script src="{% static 'js/main.js' %}"></script>
{% endblock script %}

userprofiles/templates/userprofiles/profile.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %} {{ user_obj.username}}({{ user_obj }}) {% endblock title %}

{% block content %}
  <div class="container-acc pfl-col">
    <div class="pfl-col__header">
      <div class="pfl-col__img-container">
        <a 
          {% if request.user == user_obj %} 
            title="Change your profile Picture" href="{% url 'userprofiles:profile_edit' %}" 
          {% else %}
            title="View Image" href="{{ user_obj.profile.image.url }}"
          {% endif %}
        >
          <img src="{{ user_obj.profile.image.url }}" alt="profile image" class="pfl-col__img" />
        </a>
      </div>
      <div class="pfl-col__user">
        <p class="fullname">{{ user_obj }}</p>
        <p class="username">{{ user_obj.username }}</p>
        {% if request.user == user_obj %}
        <p>
          <a href="{% url 'userprofiles:profile_edit' %}" class="edit-link">Edit Profile</a>
        </p>
        {% endif %}
      </div>
    </div>
    {% if user_obj.profile.bio %}
      <div class="pfl-col__bio">
        <p>{{ user_obj.profile.bio }}</p>
      </div>
    {% endif %}
    <div class="pfl-col__info">
      <div class="pfl-col__info-heading">
        <p>Activity Summary</p>
      </div>
      <!-- <hr /> -->
      <!-- <div class="pfl-col__info-row">
        <span>Published Posts</span> 
        <a href="{% url 'userprofiles:user_published_posts' username=user_obj.username %}">
          {{ num_published }} Post{{ num_published|pluralize }}
        </a>
      </div>
      <div class="pfl-col__info-row">
        <span>Comments:</span>
        <a href="{% url 'userprofiles:user_comments' username=user_obj.username %}">
          {{ num_comments }} Comment{{ num_comments|pluralize }}
        </a>
      </div>
      {% if request.user == user_obj %}
        <div class="pfl-col__info-row">
          <span>Drafted Posts:</span>
          <a href="{% url 'userprofiles:user_drafted_posts' %}">{{ num_drafted }} Post{{ num_drafted|pluralize }}</a>
        </div>
        <div class="pfl-col__info-row">
          <span>Liked Posts:</span> 
          <a href="{% url 'userprofiles:user_liked_posts' %}">{{ num_liked }} Post{{ num_liked|pluralize }}</a>
        </div>
        <div class="pfl-col__info-row">
          <span>Disliked Posts:</span> 
          <a href="{% url 'userprofiles:user_disliked_posts' %}">{{ num_disliked }} Post{{ num_disliked|pluralize }}</a>
        </div>
      {% endif %} -->
      <div> 
        <a class="pfl-col__info-row" href="{% url 'userprofiles:user_published_posts' username=user_obj.username %}">
          Published Posts ({{ num_published }} Post{{ num_published|pluralize }})
        </a>
        <a class="pfl-col__info-row" href="{% url 'userprofiles:user_comments' username=user_obj.username %}">
          Comments ({{ num_comments }} Comment{{ num_comments|pluralize }})
        </a>
        {% if request.user == user_obj %}
          <a class="pfl-col__info-row" href="{% url 'userprofiles:user_drafted_posts' %}">
            Drafted Posts ({{ num_drafted }} Post{{ num_drafted|pluralize }})
          </a>
          <a class="pfl-col__info-row" href="{% url 'userprofiles:user_liked_posts' %}">
            Liked Posts ({{ num_liked }} Post{{ num_liked|pluralize }})
          </a> 
          <a class="pfl-col__info-row" href="{% url 'userprofiles:user_disliked_posts' %}">
            Disliked Posts ({{ num_disliked }} Post{{ num_disliked|pluralize }})
          </a>
        {% endif %}
      </div>
  </div>
{% endblock content %}

userprofiles/templates/userprofiles/profile_edit.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %} Profile Edit {% endblock title %}

{% block content %}
  <div class="container-acc pfl-col">
    <div class="pfl-col__header">
      <h2>Edit Your Profile</h2>
    </div>
    <div class="pfl-col__info">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in user_form %}
          <div class="form-row">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
          </div>
        {% endfor %}
        {% for field in profile_form %}
          <div class="form-row">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
          </div>
        {% endfor %}
        <div class="form-row">
          <button type="submit" class="submit-button">Update Profile</button>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}